/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ChatContent: typeof import('./src/components/layout/ChatContent.vue')['default']
    ChatList: typeof import('./src/components/layout/ChatList.vue')['default']
    ChatTop: typeof import('./src/components/layout/ChatTop.vue')['default']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    IEpCaretRight: typeof import('~icons/ep/caret-right')['default']
    IEpCirclePlus: typeof import('~icons/ep/circle-plus')['default']
    IEpDocument: typeof import('~icons/ep/document')['default']
    IEpInfoFilled: typeof import('~icons/ep/info-filled')['default']
    IEpMic: typeof import('~icons/ep/mic')['default']
    IEpMore: typeof import('~icons/ep/more')['default']
    IEpMoreFilled: typeof import('~icons/ep/more-filled')['default']
    Menu: typeof import('./src/components/layout/Menu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Verify: typeof import('./src/components/verifition/Verify.vue')['default']
    VerifyPoints: typeof import('./src/components/verifition/Verify/VerifyPoints.vue')['default']
    VerifySlide: typeof import('./src/components/verifition/Verify/VerifySlide.vue')['default']
  }
}
