/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ChatContent: typeof import('./src/components/layout/ChatContent.vue')['default']
    ChatList: typeof import('./src/components/layout/ChatList.vue')['default']
    ChatTop: typeof import('./src/components/layout/ChatTop.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    IEpCaretRight: typeof import('~icons/ep/caret-right')['default']
    IEpCirclePlus: typeof import('~icons/ep/circle-plus')['default']
    IEpDocument: typeof import('~icons/ep/document')['default']
    IEpMic: typeof import('~icons/ep/mic')['default']
    Menu: typeof import('./src/components/layout/Menu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
